templateVersion: 1.0.0
ignore: true
defaultVersion: postgresql-v2.6.2
documentation: https://umami.is/docs/getting-started
type: umami
name: Umami
subname: (PostgreSQL)
description: A simple, easy to use, self-hosted web analytics solution.
services:
  $$id:
    name: Umami
    depends_on:
      - $$id-postgresql
    image: ghcr.io/umami-software/umami:$$core_version
    volumes: []
    environment:
      - ADMIN_PASSWORD=$$secret_admin_password
      - DATABASE_URL=$$secret_database_url
      - DATABASE_TYPE=$$config_database_type
      - HASH_SALT=$$secret_hash_salt
    ports:
      - '3000'
  $$id-postgresql:
    name: PostgreSQL
    depends_on: []
    image: postgres:12-alpine
    volumes:
      - $$id-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$$config_postgres_user
      - POSTGRES_PASSWORD=$$secret_postgres_password
      - POSTGRES_DB=$$config_postgres_db
    ports: []
variables:
  - id: $$secret_database_url
    name: DATABASE_URL
    label: Database URL for PostgreSQL
    defaultValue: >-
      postgresql://$$config_postgres_user:$$secret_postgres_password@$$id-postgresql:5432/$$config_postgres_db
    description: ''
  - id: $$secret_hash_salt
    name: HASH_SALT
    label: Hash Salt
    defaultValue: $$generate_hex(64)
    description: ''
  - id: $$config_database_type
    name: DATABASE_TYPE
    label: Database Type
    defaultValue: postgresql
    description: ''
  - id: $$config_postgres_user
    name: POSTGRES_USER
    label: PostgreSQL User
    defaultValue: $$generate_username
    description: ''
  - id: $$secret_postgres_password
    name: POSTGRES_PASSWORD
    label: PostgreSQL Password
    defaultValue: $$generate_password
    description: ''
  - id: $$config_postgres_db
    name: POSTGRES_DB
    label: PostgreSQL Database
    defaultValue: umami
    description: ''
  - id: $$secret_admin_password
    name: ADMIN_PASSWORD
    label: Initial Admin Password
    defaultValue: $$generate_password
    description: ''
    showOnConfiguration: true
